"""
Autoregressive extrapolation
"""


#[

from __future__ import annotations

from typing import (TYPE_CHECKING, )
from numbers import (Number, )
import numpy as _np
import scipy as _sp
import documark as _dm

from ..periods import Period
from ._functionalize import FUNC_STRING

if TYPE_CHECKING:
    from typing import Iterable
    from numbers import Real

#]


#-------------------------------------------------------------------------------
# Mixin methods
#-------------------------------------------------------------------------------


class Mixin:
    #[

    @_dm.reference(category="homogenizing", add_heading=False, )
    def extrapolate(
        self: Self,
        ar_coeffs: Iterable[Real],
        span: Iterable[Period],
        *,
        intercept: Real = 0,
        log: bool = False,
    ) -> None:
        r"""
................................................................................

## `extrapolate`

==Fills a span of periods with values generated by an autoregressive process started from the observations already in the series.==

    self.extrapolate(
        ar_coeffs,
        span,
        *,
        intercept=0,
        log=False,
    )

Use it to carry a series past its last observation on an assumed rule
rather than on new data. The observations immediately before the first
period of `span` supply the starting values, one for each coefficient.
A `span` covering periods that already carry data overwrites them.


**Input arguments.**


???+ input "ar_coeffs"
    The autoregressive coefficients as they appear on the right-hand
    side of the process, first lag first, so `[0.5, 0.25]` means each
    value is half the previous one plus a quarter of the one before
    that. A single number is accepted for a first-order process.

???+ input "span"
    The stretch of periods to fill. It is required, and it need not lie
    beyond the existing data.

???+ input "intercept"
    Added at every period. `0` when left alone.

???+ input "log"
    With `log=True` the series is logarithmised before the process is
    applied and exponentiated afterwards, which turns the additive
    process into a multiplicative one.


An empty series, or an empty `span`, is left untouched. If any starting
value is missing the process yields missing values, and those are
written to `span` regardless: at the end of the series they are trimmed
off and it comes back shorter than it went in, in the middle they stay
as gaps.


### Returns


Nothing; the series is modified in place.


### Examples


Carrying a series one year forward under the process $x_t = 0.5 \, x_{t-1}$:

    >>> import numpy as np
    >>> import datapie as dp
    >>> x = dp.Series(start=dp.qq(2020, 1),
    ...     values=np.array([1., 2., 3., 4.]))
    >>> x.extrapolate([0.5], dp.Span(dp.qq(2021, 1), dp.qq(2021, 4)))
    >>> x.get_data()[:, 0].tolist()
    [1.0, 2.0, 3.0, 4.0, 2.0, 1.0, 0.5, 0.25]

A `span` covering periods that already carry data overwrites them:

    >>> x = dp.Series(start=dp.qq(2020, 1),
    ...     values=np.array([1., 2., 3., 4.]))
    >>> x.extrapolate([0.5], dp.Span(dp.qq(2020, 3), dp.qq(2020, 4)))
    >>> x.get_data()[:, 0].tolist()
    [1.0, 2.0, 1.0, 0.5]


### Algorithm


The new observations are created using this $p$-th order autoregressive
process defined recursively as:

$$
x_t = \rho_1 \, x_{t-1} + \cdots + \rho_p \, x_{t-p} + c, \qquad t = 1, \dots, T
$$

where

* the initial conditions $x_{0},\ x_{-1}, \, \dots,\ x_{-p+1}$ are taken
from the existing observations in the input series;

* the autoregressive coefficients $\rho_1,\ \rho_2,\ \dots,\ \rho_p$ are
given by the input argument `ar_coeffs`;

* $c$ is the `intercept`.

................................................................................
        """
        if self.start is None:
            return
        span = self.resolve_periods(span, )
        if not span:
            return
        num_periods = len(span)
        ar_coeffs = (ar_coeffs, ) if isinstance(ar_coeffs, Number) else ar_coeffs
        order = len(ar_coeffs)
        ar = (1, ) + tuple(-i for i in ar_coeffs)
        start = span[0]
        initial_from_until = (start-order, start-1, )
        iter_initial_data = self.iter_own_data_variants_from_until(initial_from_until, )
        new_data = _np.hstack(tuple(
            _extrapolate_data(
                initial_data, num_periods, ar,
                intercept=intercept,
                log=log,
            )
            for initial_data in iter_initial_data
        ))
        self.set_data(span, new_data, )

    #]


#-------------------------------------------------------------------------------
# Functional forms
#-------------------------------------------------------------------------------


_functional_forms = {"extrapolate", }

for n in _functional_forms:
    code = FUNC_STRING.format(n=n, )
    exec(code, globals(), locals(), )

__all__ = tuple(_functional_forms)


#-------------------------------------------------------------------------------


def _extrapolate_data(
    initial: _np.ndarray,
    num_periods: int,
    ar: Iterable[Real],
    *,
    intercept: Real = 0,
    log: bool = False,
) -> None:
    """
    """
    #[
    initial = _np.flip(initial.flatten(), )
    if log:
        initial = _np.log(initial)
    innovation = _np.full((num_periods, ), intercept, dtype=_np.float64, )
    ma = (1, )
    zi = _sp.signal.lfiltic(ma, ar, initial, )
    out, *_ = _sp.signal.lfilter(ma, ar, innovation, zi=zi, axis=0, )
    if log:
        out = _np.exp(out)
    return out.reshape(-1, 1, )
    #]


