"""
Autoregressive extrapolation
"""


#[

from __future__ import annotations

from typing import (TYPE_CHECKING, )
from numbers import (Number, )
import numpy as _np
import scipy as _sp
import documark as _dm

from ..periods import Period
from ._functionalize import FUNC_STRING

if TYPE_CHECKING:
    from typing import Iterable
    from numbers import Real

#]


#-------------------------------------------------------------------------------
# Mixin methods
#-------------------------------------------------------------------------------


class Mixin:
    #[

    @_dm.reference(category="homogenizing", )
    def extrapolate(
        self: Self,
        ar_coeffs: Iterable[Real],
        span: Iterable[Period],
        *,
        intercept: Real = 0,
        log: bool = False,
    ) -> None:
        r"""
......................................................................

==Extrapolate time series using autoregressive process==


### Functional forms creating a new time `Series` object ###


new = extrapolate(
    self,
    ar_coeffs,
    span,
    *,
    intercept=0,
    log=False,
)


### Class method changing an existing time `Series` object in-place ###


self.extrapolate(
    ar_coeffs,
    span,
    *,
    intercept=0,
    log=False,
)


### Input arguments ###


???+ input "self"
The time `Series` object to be extrapolated by an autoregressive process.

???+ input "ar_coeffs"
The autoregressive coefficients to be used in the extrapolation, entered as
a tuple of AR_1, AR_2, ..., AR_p coefficients as if on the RHS of the AR
process definition; see Details below.

???+ input "span"
The time span on which the time series will be extrapolated.

???+ input "intercept"
The intercept in the autorergressive process.

???+ input "log"
If `log=True`, the time series will be logarithmized before the
extrapolation and then delogarithmized back.


### Returns ###


???+ returns "self"
The existing time `Series` object with its values replaced in-place.

???+ returns "new"
A new time `Series` object.


### Details ###


The new extrapolated observations are created using this $p$-th order
autoregressive process defined recursively as:

$$
x_t = \rho_1 \, x_{t-1} + \cdots + \rho_p \, x_{t-p} + c, \qquad t = 1, \dots, T
$$

where

* the initial condion $x_{0},\ x_{-1}, \, \dots,\ x_{-p+1}$ are taken from
the existing observations in the input series `self`;

* the autoregressive coefficents
$\rho_1,\ \rho_2,\ \dots,\ \rho_p$ given by the input argument `ar_coeff`

* $c$ is the `intercept`.

......................................................................
        """
        if self.start is None:
            return
        span = self.resolve_periods(span, )
        if not span:
            return
        num_periods = len(span)
        ar_coeffs = (ar_coeffs, ) if isinstance(ar_coeffs, Number) else ar_coeffs
        order = len(ar_coeffs)
        ar = (1, ) + tuple(-i for i in ar_coeffs)
        start = span[0]
        initial_from_until = (start-order, start-1, )
        iter_initial_data = self.iter_own_data_variants_from_until(initial_from_until, )
        new_data = _np.hstack(tuple(
            _extrapolate_data(
                initial_data, num_periods, ar,
                intercept=intercept,
                log=log,
            )
            for initial_data in iter_initial_data
        ))
        self.set_data(span, new_data, )

    # ==========================================================================
    #  ### `extrapolate(ar_coeffs, span, *, intercept=0, log=False)`
    #
    #  Fills a span of periods with values generated by an autoregressive
    #  process started from the observations already in the series.
    #
    #  Use it to carry a series past its last observation on an assumed
    #  rule rather than on new data. The observations immediately before
    #  the first period of `span` supply the starting values, one for each
    #  coefficient.
    #
    #  **Parameters.** `ar_coeffs` are the coefficients as they appear on
    #  the right-hand side of the process, first lag first, so `[0.5, 0.25]`
    #  means each value is half the previous one plus a quarter of the one
    #  before that.
    # 
    #  `span` is the stretch of periods to fill, and is required.
    # 
    #  `intercept` is added at every period and is `0` when left alone.
    # 
    #  With `log=True` the series is logarithmised before the
    #  process is applied and exponentiated afterwards.
    #
    #  **Returns.** Nothing; the series is modified in place. An empty
    #  series or an empty `span` is left untouched.
    #
    #  If any starting value is missing the process yields missing values,
    #  which are written to `span` regardless: at the end of the series
    #  they are trimmed off and it comes back shorter than it went in, in
    #  the middle they stay as gaps.
    #
    #  **Examples.** Carrying a series one year forward under the process
    #  `x_t = 0.5 x_{t-1}`:
    #
    #      >>> import numpy as np
    #      >>> import datapie as dp
    #      >>> x = dp.Series(start=dp.qq(2020, 1),
    #      ...     values=np.array([1., 2., 3., 4.]))
    #      >>> x.extrapolate([0.5], dp.Span(dp.qq(2021, 1), dp.qq(2021, 4)))
    #      >>> x.get_data()[:, 0].tolist()
    #      [1.0, 2.0, 3.0, 4.0, 2.0, 1.0, 0.5, 0.25]
    #
    #  A `span` covering periods that already carry data overwrites them:
    #
    #      >>> x = dp.Series(start=dp.qq(2020, 1),
    #      ...     values=np.array([1., 2., 3., 4.]))
    #      >>> x.extrapolate([0.5], dp.Span(dp.qq(2020, 3), dp.qq(2020, 4)))
    #      >>> x.get_data()[:, 0].tolist()
    #      [1.0, 2.0, 1.0, 0.5]
    #
    # ==========================================================================

    #]


#-------------------------------------------------------------------------------
# Functional forms
#-------------------------------------------------------------------------------


_functional_forms = {"extrapolate", }

for n in _functional_forms:
    code = FUNC_STRING.format(n=n, )
    exec(code, globals(), locals(), )

__all__ = tuple(_functional_forms)


#-------------------------------------------------------------------------------


def _extrapolate_data(
    initial: _np.ndarray,
    num_periods: int,
    ar: Iterable[Real],
    *,
    intercept: Real = 0,
    log: bool = False,
) -> None:
    """
    """
    #[
    initial = _np.flip(initial.flatten(), )
    if log:
        initial = _np.log(initial)
    innovation = _np.full((num_periods, ), intercept, dtype=_np.float64, )
    ma = (1, )
    zi = _sp.signal.lfiltic(ma, ar, initial, )
    out, *_ = _sp.signal.lfilter(ma, ar, innovation, zi=zi, axis=0, )
    if log:
        out = _np.exp(out)
    return out.reshape(-1, 1, )
    #]


